FIX- Log for debugging

diff --git a/.github/workflows/3-Simple API call.yaml b/.github/workflows/3-Simple API call.yaml
--- a/.github/workflows/3-Simple API call.yaml
+++ b/.github/workflows/3-Simple API call.yaml
@@ -23,7 +23,13 @@ jobs:
           TIMESTAMP=$(date +%s)
           OUTPUT_FILE="stage/${TIMESTAMP}.csv"
           mkdir -p stage
-          curl -s -H "User-Agent: Chrome/123.0" https://www.sahamyab.com/guest/twiter/list?v=0.1 | jq '.items[] | [.id, .sendTime, .sendTimePersian, .senderName, .senderUsername, .type, .content] | join(",") ' > $OUTPUT_FILE
+          RESPONSE=$(curl -s -H "User-Agent: Chrome/123.0" https://www.sahamyab.com/guest/twiter/list?v=0.1)
+          echo "Response: $RESPONSE"  # چاپ خروجی API
+          if [ $? -ne 0 ]; then
+            echo "Failed to fetch data"
+            exit 1
+          fi
+          echo "$RESPONSE" | jq '.items[] | [.id, .sendTime, .sendTimePersian, .senderName, .senderUsername, .type, .content] | join(",") ' > $OUTPUT_FILE
           echo "Data saved to $OUTPUT_FILE"
 
       - name: Commit and push changes
